name: Check lint and test status
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - run: make install
      - run: make lint
      - run: make test